#!/usr/bin/env python3

# For licensing information, see the "LICENSE" text file
import getpass as gp
import subprocess as sp

username = gp.getuser()

def call(cmd: str):
	sp.call(cmd, shell=True)

call('chmod +x mcbt')

python_path = sp.check_output('which python', shell=True)
python_path = str(python_path.decode()[:-1])

# plist file for a backround process
plist = f'''
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>com.{username}.mcbt</string>

	<key>RunAtLoad</key>
	<true/>

	<key>ProgramArguments</key>
	<array>
		<string>{python_path}</string>
		<string>mcbt</string>
	</array>

	<key>WorkingDirectory</key>
	<string>/Users/{username}/mcbt</string>

	<key>KeepAlive</key>
	<true/>
</dict>
</plist>
'''

with open(f'com.{username}.mcbt.plist', 'w') as f:
	f.write(plist)


# Remove old mcbt agent
try:
	call(f'launchctl unload ~/Library/LaunchAgents/com.{username}.mcbt.plist')
	call(f'rm ~/Library/LaunchAgents/com.{username}.mcbt.plist')
except Exception as e:
	print('err:', e)

# Move new mcbt agent to LaunchAgents
call(f'mv com.{username}.mcbt.plist ~/Library/LaunchAgents')

# Load new agent
call(f'launchctl load ~/Library/LaunchAgents/com.{username}.mcbt.plist')