#!/usr/bin/env python3

# For licensing information, see the "LICENSE" text file
import getpass as gp
import subprocess as sp
from mcbt import WORLDS_FOLDER, BACKUP_DESTINATION

username = gp.getuser()

def call(cmd: str):
	sp.call(cmd, shell=True)

call('chmod +x mcbt.py')

call(f'chmod -R 777 "{WORLDS_FOLDER}"')
call(f'chmod -R 777 "{BACKUP_DESTINATION}"')


# plist file for a backround process
plist = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.{username}.mcbt</string>
    <key>Program</key>
    <string>/Users/{username}/mcbt/mcbt.py</string>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
</dict>
</plist>
"""

with open(f'com.{username}.mcbt.plist', 'w') as f:
	f.write(plist)

# Remove old mcbt agent
call(f'launchctl stop com.{username}.mcbt.plist')
call(f'launchctl unload com.{username}.mcbt.plist')
call(f'rm ~/Library/LaunchAgents/com.{username}.mcbt.plist')
call('clear')

# Move new mcbt agent to LaunchAgents
call(f'mv com.{username}.mcbt.plist ~/Library/LaunchAgents')

# Load new agent
call(f'launchctl load ~/Library/LaunchAgents/com.{username}.mcbt.plist')
call(f'launchctl start com.{username}.mcbt.plist')